version: '3.8'
services:

  dev-db:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_DB: nest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    networks:
      - app-network

  app:
    build: .
    ports:
      - '4000:4000'
    depends_on:
      - dev-db
    env_file:
      - .env
    volumes:
      - ./src:/app/src
    networks:
      - app-network

networks:
  app-network:
    driver: bridge